# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters: 
                thumbnail  : { size : [400, 319], mode : outbound}
                #background : { size : [124, 94], position : center, color : '#000000' }
        medium:
            quality: 75
            filters: 
                thumbnail  : { size : [720, 477], mode : outbound}
                #background : { size : [124, 94], position : center, color : '#000000' }
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
